package com.data.pojo;

public class TUser {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_user.user_id
     *
     * @mbg.generated dd
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_user.user_age
     *
     * @mbg.generated dd
     */
    private String userAge;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_user.user_name
     *
     * @mbg.generated dd
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbg.generated dd
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbg.generated dd
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_user.user_age
     *
     * @return the value of t_user.user_age
     *
     * @mbg.generated dd
     */
    public String getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * t_user.user_age
     *
     * @param userAge the value for t_user.user_age
     *
     * @mbg.generated dd
     */
    public void setUserAge(String userAge) {
        this.userAge = userAge == null ? null : userAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbg.generated dd
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbg.generated dd
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}
